-- Listing 10-14. Convenient Procedure for Getting Network Details
CREATE OR REPLACE PROCEDURE SHOW_NET_DETAILS (NETWORK_NAME VARCHAR2) AS
BEGIN
  DBMS_OUTPUT.PUT_LINE ('Details on Network ' || NETWORK_NAME);
  DBMS_OUTPUT.PUT_LINE ('NETWORK_EXISTS() =             ' || SDO_NET.NETWORK_EXISTS(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('IS_HIERARCHICAL() =            ' || SDO_NET.IS_HIERARCHICAL(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('IS_LOGICAL() =                 ' || SDO_NET.IS_LOGICAL(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('IS_SPATIAL() =                 ' || SDO_NET.IS_SPATIAL(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_NETWORK_CATEGORY() =       ' || SDO_NET.GET_NETWORK_CATEGORY(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('SDO_GEOMETRY_NETWORK() =       ' || SDO_NET.SDO_GEOMETRY_NETWORK(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_NETWORK_TYPE() =           ' || SDO_NET.GET_NETWORK_TYPE(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_GEOMETRY_TYPE() =          ' || SDO_NET.GET_GEOMETRY_TYPE(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_NO_OF_HIERARCHY_LEVELS() = ' || SDO_NET.GET_NO_OF_HIERARCHY_LEVELS(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_LINK_DIRECTION() =         ' || SDO_NET.GET_LINK_DIRECTION(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_NODE_TABLE_NAME() =        ' || SDO_NET.GET_NODE_TABLE_NAME(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_NODE_COST_COLUMN() =       ' || SDO_NET.GET_NODE_COST_COLUMN(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_NODE_GEOM_COLUMN() =       ' || SDO_NET.GET_NODE_GEOM_COLUMN(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_LINK_TABLE_NAME() =        ' || SDO_NET.GET_LINK_TABLE_NAME(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_LINK_COST_COLUMN() =       ' || SDO_NET.GET_LINK_COST_COLUMN(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_LINK_GEOM_COLUMN() =       ' || SDO_NET.GET_LINK_GEOM_COLUMN(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_PATH_TABLE_NAME() =        ' || SDO_NET.GET_PATH_TABLE_NAME(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_PATH_GEOM_COLUMN() =       ' || SDO_NET.GET_PATH_GEOM_COLUMN(NETWORK_NAME));
  DBMS_OUTPUT.PUT_LINE ('GET_PATH_LINK_TABLE_NAME() =   ' || SDO_NET.GET_PATH_LINK_TABLE_NAME(NETWORK_NAME));
END;
/
