-- Listing D-3. Creating the Raster Data Table
CREATE TABLE branches_rdt OF SDO_RASTER
(
  PRIMARY KEY
  (
    RASTERID, PYRAMIDLEVEL, BANDBLOCKNUMBER,
    ROWBLOCKNUMBER, COLUMNBLOCKNUMBER
  )
)
LOB(RASTERBLOCK) STORE AS (NOCACHE NOLOGGING);
