-- Listing 5-12. Transporting the Tablespace TBS from a Source Database
CONNECT SPATIAL/SPATIAL
EXECUTE SDO_UTIL.PREPARE_FOR_TTS('TBS');
CONNECT SYSTEM/MANAGER AS SYSDBA
EXECUTE DBMS_TTS.TRANSPORT_SET_CHECK('TBS', TRUE);
ALTER TABLESPACE TBS READ ONLY;
EXIT;
