-- Listing 7-5. Point Constructor Function
CREATE OR REPLACE FUNCTION point (
  x NUMBER, y NUMBER, srid NUMBER DEFAULT 8307)
RETURN SDO_GEOMETRY
DETERMINISTIC
IS
BEGIN
  RETURN SDO_GEOMETRY (
          2001, srid, SDO_POINT_TYPE (x,y,NULL), NULL, NULL);
END;
/
